In [4]:
# %pip install point-cloud-utils
# %pip install open3d

In [5]:
import open3d as o3d
import numpy as np
import point_cloud_utils as pcu

# Filter GT car point cloud with coordinate boundings

In [6]:
#sample_pcd_data = o3d.data.PCDPointCloud()
pcd_gt = o3d.io.read_point_cloud("garage_car_gt.ply")#
print(pcd_gt)
# o3d.io.write_point_cloud("garage_car_gt.pcd", pcd)

points = np.asarray(pcd_gt.points)
print(points[:10])

min_x = points[:,0].min()
max_x = points[:,0].max()
min_y = points[:,1].min()
max_y = points[:,1].max()
min_z = points[:,2].min()
max_z = points[:,2].max()

height = max_z - min_z
print(f'height is: {height}')

filtered_points = []
for p in points:
    if (p[0] < min_x + 0.54*(max_x-min_x)) \
    and (p[0] > min_x + 0.33*(max_x-min_x)) \
    and (p[1] < min_y + 0.60*(max_y-min_y))\
    and (p[1] > min_y + 0.167*(max_y-min_y)) \
    and (p[2] < min_z + 0.37*height) \
    and (p[2] > min_z + 0.05*height):
        filtered_points.append(p)

pcd_gt.points = o3d.utility.Vector3dVector(filtered_points)

pcd_gt.normals = o3d.utility.Vector3dVector(np.zeros((1,3)))
pcd_gt.estimate_normals()
o3d.visualization.draw_geometries([pcd_gt], point_show_normal=True)


PointCloud with 47028 points.
[[-4.20962906 -4.486413   -0.48271599]
 [-4.20279646 -4.48939323 -0.57438207]
 [-4.21632767 -4.52246857 -0.52107489]
 [-4.22232676 -4.49640751 -0.4567422 ]
 [-4.21476746 -4.47093773 -0.3922652 ]
 [-4.22053099 -4.48530102 -0.4077765 ]
 [-4.219666   -4.39975834 -0.22369796]
 [-4.21847248 -4.44138527 -0.30374253]
 [-4.23277807 -4.44536114 -0.2040692 ]
 [-4.18092203 -4.35640526 -1.03531718]]
height is: 4.613835334777832


In [4]:
print(pcd_gt.normals)

std::vector<Eigen::Vector3d> with 8295 elements.
Use numpy.asarray() to access data.


In [6]:
radii =  [0.2, 0.2, 0.02, 0.04]
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd_gt, o3d.utility.DoubleVector(radii))

o3d.io.write_triangle_mesh("gt_garage_car_cropped.ply", rec_mesh)

True

In [ ]:
mesh_gt_poisson, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
        pcd_gt, depth=4)
o3d.visualization.draw_geometries([mesh_gt_poisson], point_show_normal=True)

In [4]:
bbox_gt = pcd_gt.get_axis_aligned_bounding_box()
bbox_gt.color = (1, 0, 0)
o3d.visualization.draw_geometries([pcd_gt, bbox_gt])

In [5]:
# viewer = o3d.visualization.Visualizer()
# viewer.create_window()

# viewer.add_geometry(pcd)
# opt = viewer.get_render_option()
# opt.show_coordinate_frame = True
# viewer.run()
# viewer.destroy_window()
o3d.visualization.draw_geometries([pcd_gt])

In [6]:
points = np.asarray(pcd_gt.points)
print(points[:10])

min_x = points[:,0].min()
max_x = points[:,0].max()
min_y = points[:,1].min()
max_y = points[:,1].max()
min_z = points[:,2].min()
max_z = points[:,2].max()

print(max_x - min_x)
print(max_y - min_y)
print(max_z - min_z)

[[-2.45406628e-02 -7.77081251e-01 -7.14078307e-01]
 [-9.10775661e-02 -7.49493122e-01 -7.13989735e-01]
 [-1.03873968e-01 -7.82091379e-01 -7.09087014e-01]
 [ 8.08477402e-04 -8.21151733e-01 -7.04544902e-01]
 [-4.19430733e-02 -8.37680340e-01 -6.75761521e-01]
 [-4.64873314e-02 -7.36751318e-01 -7.71771431e-01]
 [-1.11173153e-01 -6.97208881e-01 -7.70535469e-01]
 [-9.56075191e-02 -6.91247940e-01 -8.24461937e-01]
 [-1.32336140e-01 -6.45476103e-01 -8.23509812e-01]
 [-4.26802635e-02 -7.25002050e-01 -8.04933071e-01]]
1.8494912385940552
4.1528595089912415
1.466355562210083


In [7]:
bbox_gt.dimension


<bound method PyCapsule.dimension of AxisAlignedBoundingBox: min: (-1.49703, -3.24676, -2.06633), max: (0.352458, 0.9061, -0.59997)>

In [116]:
print(type(pcd_gt))
radii =  [0.005, 0.01, 0.02, 0.04]
rec_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd_gt, o3d.utility.DoubleVector(radii))

o3d.io.write_triangle_mesh("gt_garage_car_cropped.ply", rec_mesh)

<class 'open3d.cpu.pybind.geometry.PointCloud'>


RuntimeError: [Open3D ERROR] ReconstructBallPivoting requires normals

In [122]:
mesh_gt_from_pcd = o3d.geometry.TriangleMesh.create_from_point_cloud_alpha_shape(pcd_gt, 0.3)
o3d.visualization.draw_geometries([mesh_gt_from_pcd], mesh_show_back_face=True)

In [9]:
# Filter in the same way but with mesh

mesh_gt = o3d.io.read_triangle_mesh("garage_car_gt.ply")

# o3d.io.write_point_cloud("garage_car_gt.pcd", pcd)

vertices = mesh_gt.vertices
normals = mesh_gt.normals
print(points[:10])

min_x = points[:,0].min()
max_x = points[:,0].max()
min_y = points[:,1].min()
max_y = points[:,1].max()
min_z = points[:,2].min()
max_z = points[:,2].max()

height = max_z - min_z
print(f'height is: {height}')

filtered_vertices = []
filtered_normals = []
for v,f in zip(vertices,faces):
    if (v[0] < min_x + 0.54*(max_x-min_x)) \
    and (v[0] > min_x + 0.33*(max_x-min_x)) \
    and (v[1] < min_y + 0.60*(max_y-min_y))\
    and (v[1] > min_y + 0.167*(max_y-min_y)) \
    and (v[2] < min_z + 0.37*height) \
    and (v[2] > min_z + 0.05*height):
        filtered_vertices.append(v)
        filtered_normals.append(v)

mesh_gt.vertices = filtered_vertices
mesh_gt.normals = filtered_normals

AttributeError: 'open3d.cpu.pybind.geometry.TriangleMesh' object has no attribute 'normals'

In [15]:
mesh, densities = o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(
        pcd_gt, depth=9)

RuntimeError: [Open3D ERROR] [CreateFromPointCloudPoisson] pcd has no normals

In [14]:
print(np.asarray(mesh_gt.triangles))

[[ 6627  6628  6625]
 [33275  6628  6627]
 [ 6628  6629  6625]
 ...
 [38543 38544 38546]
 [  687   686 24080]
 [20626  5115  5141]]


In [ ]:
#visulaizing .pcd
print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()
pcd_gt = o3d.io.read_point_cloud("garage_car_gt.ply")
pcd1 = o3d.io.read_point_cloud("garage_car_slam.pcd")
#print(pcd)
#print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])
o3d.visualization.draw_geometries([pcd1])


aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1, 0, 0)
aabb1 = pcd1.get_axis_aligned_bounding_box()
aabb1.color = (1, 0, 0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0, 1, 0)
obb1 = pcd.get_oriented_bounding_box()
obb1.color = (0, 1, 0)

x = np.asarray(obb.get_box_points())
print(x)

obb.volume()


In [3]:
#re arranging corrdinates
import numpy as np
from open3d import *
from open3d.utility import Vector3dVector

# Load the point cloud data file
pcd = o3d.io.read_point_cloud("new_arch_atlas.pcd")

# Convert the point cloud data into a numpy array
points = np.asarray(pcd.points)

# Compute the mean of each coordinate axis
mean = np.mean(points, axis=0)

# Subtract the mean values from each coordinate
points -= mean

# Update the point cloud data with the new coordinates
pcd.points = Vector3dVector(points)

# Save the updated point cloud data to a new .pcd file
o3d.io.write_point_cloud("new_arch_atlas.pcd", pcd)


True

In [6]:
#finding IoU from .pcd

import numpy as np
from open3d import *
from sklearn.metrics import pairwise_distances

# Load the point cloud data files
pcd1 = o3d.io.read_point_cloud("ground_truth.pcd")
pcd2 = o3d.io.read_point_cloud("box4.pcd")

# Convert the point cloud data into numpy arrays
points1 = np.asarray(pcd1.points)
points2 = np.asarray(pcd2.points)
#print(points1)
# Determine the bounding boxes for each point cloud data file
bbox1 = np.array([[np.min(points1[:,0]), np.min(points1[:,1]), np.min(points1[:,2])],
                  [np.max(points1[:,0]), np.max(points1[:,1]), np.max(points1[:,2])]])
bbox2 = np.array([[np.min(points2[:,0]), np.min(points2[:,1]), np.min(points2[:,2])],
                  [np.max(points2[:,0]), np.max(points2[:,1]), np.max(points2[:,2])]])

# Compute the intersection and union volumes
intersection_vol = np.prod(np.maximum(np.zeros(3), np.minimum(bbox1[1], bbox2[1]) - np.maximum(bbox1[0], bbox2[0])))

bbox1_vol = np.prod(bbox1[1] - bbox1[0])
bbox2_vol = np.prod(bbox2[1] - bbox2[0])
union_vol = bbox1_vol + bbox2_vol - intersection_vol

# Compute the IoU score
iou = intersection_vol / union_vol

# Store the IoU score in a matrix format
iou_matrix = np.array([[iou]])
print(iou)


0.7461525077781208


In [ ]:
import matplotlib.pyplot as plt

# A = np.array([[ 1.07076887,  0.49715754,  0.83005751],
# [ 1.26622805, -0.80911457, 0.73557315],
# [ 0.27439615,  0.3752837,   0.86754558],
# [ 1.04617629,  0.52477215,  0.39740343],
# [ 0.44526275, -0.9033738,   0.34040714],
# [ 0.24980357,  0.40289831,  0.4348915 ],
# [ 1.24163547, -0.78149996,  0.30291908],
# [ 0.46985533, -0.93098841,  0.77306122]])

A = np.array([[2.34745586, 1.37485432 ,1.84188344],
 [2.45476055 ,2.59169925 ,1.74893821],
 [1.54399161 ,1.45728807 ,1.99351689],
 [2.45514538 ,1.40758388 ,2.39470775],
 [1.7589858 , 2.70686255 ,2.45339596],
 [1.65168112 ,1.49001762, 2.5463412 ],
 [2.56245006 ,2.6244288  ,2.30176252],
 [1.65129629 ,2.67413299 ,1.90057166]])

A_new = np.zeros_like(A)
A_new[0] = A[7]
A_new[1] = A[1]
A_new[2] = A[6]
A_new[3] = A[4]
A_new[4] = A[2]
A_new[5] = A[0]
A_new[6] = A[3]
A_new[7] = A[5]
print(A)

fig = plt.figure(figsize=(12, 12))
ax = fig.add_subplot(projection='3d')


#plt.plot(A[:, 0], A[:, 1], A[:, 2],'o', label = 'data')


#L = np.sqrt()

ax.plot(A_new[:, 0], A_new[:, 1], A_new[:, 2])
plt.legend()
plt.show()

In [ ]:
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

#%pip install pytorch3d
from typing import Tuple

import torch
import torch.nn.functional as F
from pytorch3d import _C
from torch.autograd import Function


# -------------------------------------------------- #
#                  CONSTANTS                         #
# -------------------------------------------------- #
"""
_box_planes and _box_triangles define the 4- and 3-connectivity
of the 8 box corners.
_box_planes gives the quad faces of the 3D box
_box_triangles gives the triangle faces of the 3D box
"""
_box_planes = [
    [0, 1, 2, 3],
    [3, 2, 6, 7],
    [0, 1, 5, 4],
    [0, 3, 7, 4],
    [1, 2, 6, 5],
    [4, 5, 6, 7],
]
_box_triangles = [
    [0, 1, 2],
    [0, 3, 2],
    [4, 5, 6],
    [4, 6, 7],
    [1, 5, 6],
    [1, 6, 2],
    [0, 4, 7],
    [0, 7, 3],
    [3, 2, 6],
    [3, 6, 7],
    [0, 1, 5],
    [0, 4, 5],
]


def _check_coplanar(boxes: torch.Tensor, eps: float = 1e-4) -> None:
    faces = torch.tensor(_box_planes, dtype=torch.int64, device=boxes.device)
    verts = boxes.index_select(index=faces.view(-1), dim=1)
    B = boxes.shape[0]
    P, V = faces.shape
    # (B, P, 4, 3) -> (B, P, 3)
    v0, v1, v2, v3 = verts.reshape(B, P, V, 3).unbind(2)

    # Compute the normal
    e0 = F.normalize(v1 - v0, dim=-1)
    e1 = F.normalize(v2 - v0, dim=-1)
    normal = F.normalize(torch.cross(e0, e1, dim=-1), dim=-1)

    # Check the fourth vertex is also on the same plane
    mat1 = (v3 - v0).view(B, 1, -1)  # (B, 1, P*3)
    mat2 = normal.view(B, -1, 1)  # (B, P*3, 1)
    if not (mat1.bmm(mat2).abs() < eps).all().item():
        msg = "Plane vertices are not coplanar"
        raise ValueError(msg)

    return


def _check_nonzero(boxes: torch.Tensor, eps: float = 1e-4) -> None:
    """
    Checks that the sides of the box have a non zero area
    """
    faces = torch.tensor(_box_triangles, dtype=torch.int64, device=boxes.device)
    verts = boxes.index_select(index=faces.view(-1), dim=1)
    B = boxes.shape[0]
    T, V = faces.shape
    # (B, T, 3, 3) -> (B, T, 3)
    v0, v1, v2 = verts.reshape(B, T, V, 3).unbind(2)

    normals = torch.cross(v1 - v0, v2 - v0, dim=-1)  # (B, T, 3)
    face_areas = normals.norm(dim=-1) / 2

    if (face_areas < eps).any().item():
        msg = "Planes have zero areas"
        raise ValueError(msg)

    return


class _box3d_overlap(Function):
    """
    Torch autograd Function wrapper for box3d_overlap C++/CUDA implementations.
    Backward is not supported.
    """

    @staticmethod
    def forward(ctx, boxes1, boxes2):
        """
        Arguments defintions the same as in the box3d_overlap function
        """
        vol, iou = _C.iou_box3d(boxes1, boxes2)
        return vol, iou

    @staticmethod
    def backward(ctx, grad_vol, grad_iou):
        raise ValueError("box3d_overlap backward is not supported")


def box3d_overlap(
    boxes1: torch.Tensor, boxes2: torch.Tensor, eps: float = 1e-4
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Computes the intersection of 3D boxes1 and boxes2.

    Inputs boxes1, boxes2 are tensors of shape (B, 8, 3)
    (where B doesn't have to be the same for boxes1 and boxes2),
    containing the 8 corners of the boxes, as follows:

        (4) +---------+. (5)
            | ` .     |  ` .
            | (0) +---+-----+ (1)
            |     |   |     |
        (7) +-----+---+. (6)|
            ` .   |     ` . |
            (3) ` +---------+ (2)


    NOTE: Throughout this implementation, we assume that boxes
    are defined by their 8 corners exactly in the order specified in the
    diagram above for the function to give correct results. In addition
    the vertices on each plane must be coplanar.
    As an alternative to the diagram, this is a unit bounding
    box which has the correct vertex ordering:

    box_corner_vertices = [
        [0, 0, 0],
        [1, 0, 0],
        [1, 1, 0],
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 1],
        [1, 1, 1],
        [0, 1, 1],
    ]

    Args:
        boxes1: tensor of shape (N, 8, 3) of the coordinates of the 1st boxes
        boxes2: tensor of shape (M, 8, 3) of the coordinates of the 2nd boxes
    Returns:
        vol: (N, M) tensor of the volume of the intersecting convex shapes
        iou: (N, M) tensor of the intersection over union which is
            defined as: `iou = vol / (vol1 + vol2 - vol)`
    """
    if not all((8, 3) == box.shape[1:] for box in [boxes1, boxes2]):
        raise ValueError("Each box in the batch must be of shape (8, 3)")

    _check_coplanar(boxes1, eps)
    _check_coplanar(boxes2, eps)
    _check_nonzero(boxes1, eps)
    _check_nonzero(boxes2, eps)

    vol, iou = _box3d_overlap.apply(boxes1, boxes2)

    return vol, iou

In [ ]:
# Calculate IoU 3D
import torch
boxes1 = torch.tensor(A_new, dtype=torch.float32)
boxes2 = torch.tensor(A_new, dtype=torch.float32)
box1 = boxes1.reshape((1,8,3))
box2 = boxes2.reshape((1,8,3))
print(box1.shape)
print(box1.shape[1:])
if not (8, 3) == box1.shape[1:]:
    raise ValueError("Each box in the batch must be of shape (8, 3)")
print(box3d_overlap(box1, box2))